name: Build DexDumper (NDK Multi-ABI)

on:
  push:
    branches: [ main, master ]
  pull_request:
    branches: [ main, master ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        abi: [armeabi-v7a, arm64-v8a, x86, x86_64]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Android NDK
        uses: nttld/setup-ndk@v1
        with:
          ndk-version: r25c

      - name: Build for ${{ matrix.abi }}
        run: |
          echo "NDK path: $ANDROID_NDK_HOME"
          $ANDROID_NDK_HOME/ndk-build NDK_PROJECT_PATH=. \
            NDK_APPLICATION_MK=./jni/Application.mk \
            APP_ABI=${{ matrix.abi }} V=1

      - name: Upload build artifacts
        uses: actions/upload-artifact@v4
        with:
          name: DexDumper-${{ matrix.abi }}
          path: libs/${{ matrix.abi }}/*
